# Generated by Django 6.1 on 2026-09-11 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_tools', '0002_aptitudequestion_aptitudeattempt_aptitudeanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_summary', models.TextField(blank=True)),
                ('strongest_area', models.CharField(blank=True, max_length=100)),
                ('improvement_area', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('reviewed', 'Reviewed')], default='generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aptitude_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_recommendations', to='career_tools.aptitudeattempt')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_recommendations', to='career_tools.careerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CareerRecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1)),
                ('career_title', models.CharField(max_length=150)),
                ('match_percentage', models.PositiveIntegerField(default=0)),
                ('reason', models.TextField(blank=True)),
                ('skills_to_improve', models.TextField(blank=True)),
                ('recommended_course', models.CharField(blank=True, max_length=200)),
                ('next_step', models.TextField(blank=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='career_tools.careerrecommendation')),
            ],
            options={
                'ordering': ['rank', 'id'],
                'constraints': [models.UniqueConstraint(fields=('recommendation', 'rank'), name='unique_recommendation_rank')],
            },
        ),
    ]
