# Generated by Django 6.1 on 2026-09-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_tools', '0003_careerrecommendation_careerrecommendationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerprofile',
            name='current_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='careerprofile',
            name='preferred_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='careerprofile',
            name='stream',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
