# Generated by Django 6.1 on 2026-09-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_tools', '0004_careerprofile_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerprofile',
            name='career_pin',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='careerprofile',
            name='career_pin_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerprofile',
            name='last_career_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
