# Generated by Django 6.1 on 2026-10-01 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_tools', '0006_careerpinresetlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCompassQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('interest', 'Interest'), ('subject', 'Subject Comfort'), ('problem_solving', 'Problem Solving'), ('work_style', 'Work Style'), ('environment', 'Career Environment')], max_length=30)),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=300)),
                ('option_b', models.CharField(max_length=300)),
                ('option_c', models.CharField(max_length=300)),
                ('option_d', models.CharField(max_length=300)),
                ('direction_a', models.CharField(max_length=30)),
                ('direction_b', models.CharField(max_length=30)),
                ('direction_c', models.CharField(max_length=30)),
                ('direction_d', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CareerCompassAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed')], default='started', max_length=20)),
                ('technology_score', models.PositiveIntegerField(default=0)),
                ('business_score', models.PositiveIntegerField(default=0)),
                ('science_score', models.PositiveIntegerField(default=0)),
                ('creative_score', models.PositiveIntegerField(default=0)),
                ('people_score', models.PositiveIntegerField(default=0)),
                ('practical_score', models.PositiveIntegerField(default=0)),
                ('top_direction', models.CharField(blank=True, max_length=30)),
                ('second_direction', models.CharField(blank=True, max_length=30)),
                ('third_direction', models.CharField(blank=True, max_length=30)),
                ('counselling_status', models.CharField(choices=[('new', 'New'), ('called', 'Called'), ('booked', 'Counselling Booked'), ('visited', 'Visited'), ('guided', 'Guidance Given'), ('converted', 'Converted')], default='new', max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_compass_attempts', to='career_tools.careerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CareerCompassAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('selected_direction', models.CharField(max_length=30)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='career_tools.careercompassattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compass_answers', to='career_tools.careercompassquestion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='unique_career_compass_answer')],
            },
        ),
    ]
