# Generated by Django 6.1 on 2026-10-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_tools', '0007_careercompassquestion_careercompassattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careercompassquestion',
            name='option_a_mr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='careercompassquestion',
            name='option_b_mr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='careercompassquestion',
            name='option_c_mr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='careercompassquestion',
            name='option_d_mr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='careercompassquestion',
            name='question_mr',
            field=models.TextField(blank=True),
        ),
    ]
