# Generated by Django 6.1 on 2026-09-28 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('core', '0046_franchiseenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentParticipantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('current_status', models.CharField(blank=True, choices=[('student', 'Student'), ('fresher', 'Fresher'), ('working', 'Working Professional'), ('business', 'Business / Self Employed'), ('other', 'Other')], max_length=30)),
                ('career_interest', models.CharField(blank=True, max_length=150)),
                ('consent_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_profiles', to='assessments.assessment')),
                ('enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_profiles', to='core.enquiry')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mobile'], name='assessments_mobile_a7f59b_idx'), models.Index(fields=['district'], name='assessments_distric_0e0a9c_idx')],
            },
        ),
    ]
