# Generated by Django 6.1 on 2026-09-28 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentattempt_participant_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('experience', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('resume_url', models.URLField(blank=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mobile'], name='assessments_mobile_65b6f6_idx'), models.Index(fields=['email'], name='assessments_email_c63b53_idx')],
            },
        ),
        migrations.CreateModel(
            name='HiringApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('intern', 'Intern'), ('part_time', 'Part-Time'), ('full_time', 'Full-Time'), ('trainer', 'Trainer')], max_length=20)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('test_pending', 'Test Pending'), ('test_completed', 'Test Completed'), ('practical_pending', 'Practical Pending'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('joined', 'Joined')], default='applied', max_length=30)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_application', to='assessments.assessmentattempt')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='assessments.hiringcandidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HiringEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('practical_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('communication_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('performance_band', models.CharField(blank=True, choices=[('not_shortlisted', 'Below 40 - Not Shortlisted'), ('trainee', '40-54 - Trainee'), ('junior', '55-69 - Junior'), ('skilled', '70-84 - Skilled'), ('advanced', '85-100 - Advanced')], max_length=30)),
                ('suggested_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suggested_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approved_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='assessments.hiringapplication')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HiringJobRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('technical_weight', models.PositiveIntegerField(default=100)),
                ('practical_weight', models.PositiveIntegerField(default=0)),
                ('communication_weight', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hiring_job_roles', to='assessments.assessment')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hiringapplication',
            name='job_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='assessments.hiringjobrole'),
        ),
        migrations.CreateModel(
            name='HiringSalaryMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('intern', 'Intern'), ('part_time', 'Part-Time'), ('full_time', 'Full-Time'), ('trainer', 'Trainer')], max_length=20)),
                ('performance_band', models.CharField(choices=[('not_shortlisted', 'Below 40 - Not Shortlisted'), ('trainee', '40-54 - Trainee'), ('junior', '55-69 - Junior'), ('skilled', '70-84 - Skilled'), ('advanced', '85-100 - Advanced')], max_length=30)),
                ('min_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_matrix', to='assessments.hiringjobrole')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job_role', 'employment_type', 'performance_band'), name='unique_hiring_salary_matrix')],
            },
        ),
    ]
