# Generated by Django 6.1 on 2026-09-28 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_hiringcandidate_hiringapplication_hiringevaluation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringInterviewProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_yourself', models.TextField()),
                ('why_mcti', models.TextField()),
                ('why_select_you', models.TextField()),
                ('strengths', models.TextField()),
                ('weakness_improving', models.TextField()),
                ('career_goals', models.TextField()),
                ('current_learning', models.TextField(blank=True)),
                ('role_interest', models.TextField()),
                ('why_train_students', models.TextField(blank=True, help_text='Primarily for trainer roles.')),
                ('job_source', models.CharField(blank=True, max_length=150)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('joining_availability', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_profile', to='assessments.hiringapplication')),
            ],
        ),
    ]
