# Generated by Django 6.1 on 2026-09-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_hiringinterviewprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('test_pending', 'Test Pending'), ('test_completed', 'Test Completed'), ('practical_pending', 'Practical Pending'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected'), ('hold', 'Hold'), ('rejected', 'Rejected'), ('joined', 'Joined')], default='applied', max_length=30),
        ),
    ]
