# Generated by Django 6.1 on 2026-09-28 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_hiringapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('awareness', 'Awareness Quiz'), ('hiring', 'Hiring Assessment'), ('staff', 'Staff Assessment'), ('placement', 'Placement Assessment'), ('scholarship', 'Scholarship Test'), ('other', 'Other')], default='awareness', max_length=30),
        ),
        migrations.CreateModel(
            name='ScholarshipResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarship_percentage', models.PositiveIntegerField(default=0)),
                ('scholarship_band', models.CharField(blank=True, max_length=100)),
                ('selected_course', models.CharField(blank=True, max_length=200)),
                ('preferred_branch', models.CharField(blank=True, max_length=100)),
                ('claim_status', models.CharField(choices=[('qualified', 'Qualified'), ('contacted', 'Contacted'), ('claimed', 'Claimed'), ('converted', 'Converted'), ('expired', 'Expired'), ('not_eligible', 'Career Guidance')], default='qualified', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('counsellor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_result', to='assessments.assessmentattempt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
