# Generated by Django 6.1 on 2026-09-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_alter_assessment_assessment_type_scholarshipresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipresult',
            name='claim_status',
            field=models.CharField(choices=[('new', 'New'), ('test_completed', 'Test Completed'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('sent_to_enquiry', 'Sent to Enquiry'), ('not_interested', 'Not Interested'), ('claimed', 'Scholarship Claimed'), ('converted', 'Converted'), ('expired', 'Expired')], default='new', max_length=20),
        ),
    ]
