# Generated by Django 6.1 on 2026-09-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_alter_scholarshipresult_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('awareness', 'Awareness Quiz'), ('hiring', 'Hiring Assessment'), ('staff', 'Staff Assessment'), ('placement', 'Placement Assessment'), ('scholarship', 'Scholarship Test'), ('exam_preparation', 'Exam Preparation'), ('other', 'Other')], default='awareness', max_length=30),
        ),
    ]
