# Generated by Django 6.1 on 2026-09-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_alter_assessment_assessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='board_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='question_origin',
            field=models.CharField(choices=[('mcti_practice', 'MCTI Practice'), ('board_based', 'Based on Board Paper'), ('board_verified', 'Verified Board Question')], default='mcti_practice', max_length=30),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='source_reference',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
