# Generated by Django 6.1 on 2026-09-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_assessmentquestion_board_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='selected_question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
