# Generated by Django 6.1 on 2026-10-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_assessmentattempt_selected_question_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentoption',
            name='option_text_hi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assessmentoption',
            name='option_text_mr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='question_text_hi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='question_text_mr',
            field=models.TextField(blank=True, default=''),
        ),
    ]
