# Generated by Django 6.1 on 2026-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('followup', 'Follow Up'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
