# Generated by Django 6.1 on 2026-08-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_enquiry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='followup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='followup_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
