# Generated by Django 6.1 on 2026-08-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_enquiry_followup_date_enquiry_followup_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
