# Generated by Django 6.1 on 2026-08-29 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_enquiry_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('note', 'Note'), ('status', 'Status Changed'), ('followup', 'Follow-up'), ('converted', 'Converted')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='core.enquiry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
