# Generated by Django 6.1 on 2026-08-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_admission_initial_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='balance_after_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='previous_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='admission',
            name='initial_payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque')], max_length=20),
        ),
    ]
