# Generated by Django 6.1 on 2026-08-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_feepayment_balance_after_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='initial_payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque')], default='cash', max_length=20),
        ),
    ]
