# Generated by Django 6.1 on 2026-08-31 15:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_admission_user_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('kharghar', 'Kharghar'), ('panvel', 'Panvel'), ('koperkhairane', 'Koperkhairane'), ('kamothe', 'Kamothe'), ('ghansoli', 'Ghansoli'), ('head_office', 'Head Office')], max_length=50)),
                ('department', models.CharField(choices=[('management', 'Management'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('training', 'Training'), ('operations', 'Operations'), ('hr', 'HR'), ('accounts', 'Accounts'), ('placement', 'Placement'), ('it', 'IT')], max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
