# Generated by Django 6.1 on 2026-09-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='branch',
            field=models.CharField(choices=[('kharghar', 'Kharghar'), ('panvel', 'Panvel'), ('koperkhairane', 'Koperkhairane'), ('kamothe', 'Kamothe'), ('ghansoli', 'Ghansoli'), ('nerul', 'Nerul'), ('head_office', 'Head Office')], max_length=50),
        ),
    ]
