# Generated by Django 6.1 on 2026-09-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_admission_address_admission_mother_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('required_skills', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('apply_link', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_mobile', models.CharField(blank=True, max_length=20)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_courses', models.ManyToManyField(blank=True, related_name='job_posts', to='core.course')),
            ],
        ),
    ]
