# Generated by Django 6.1 on 2026-09-04 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('service', models.CharField(choices=[('ai', 'AI Solutions'), ('saas', 'SaaS Solutions'), ('it', 'IT Solutions')], max_length=20)),
                ('project_requirement', models.TextField()),
                ('budget_range', models.CharField(blank=True, choices=[('below_25k', 'Below ₹25,000'), ('25k_50k', '₹25,000 - ₹50,000'), ('50k_1l', '₹50,000 - ₹1,00,000'), ('1l_3l', '₹1,00,000 - ₹3,00,000'), ('above_3l', 'Above ₹3,00,000'), ('discuss', "Let's Discuss")], max_length=30)),
                ('preferred_contact_time', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('followup', 'Follow Up'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('assigned_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('followup_notes', models.TextField(blank=True, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_business_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
