# Generated by Django 6.1 on 2026-09-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_businessleadactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslead',
            name='service',
            field=models.CharField(choices=[('ai', 'AI Solutions'), ('saas', 'SaaS Solutions'), ('it', 'IT Solutions'), ('corporate_training', 'Corporate Training')], max_length=20),
        ),
    ]
