# Generated by Django 6.1 on 2026-09-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_businesslead_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslead',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesslead',
            name='preferred_training_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesslead',
            name='training_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='businesslead',
            name='training_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
