# Generated by Django 6.1 on 2026-09-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_businesslead_employee_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='first_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('auto', 'Auto - Student Login'), ('staff', 'Staff Manual'), ('admin', 'Admin Manual')], default='auto', max_length=20),
        ),
    ]
