# Generated by Django 6.1 on 2026-09-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_branchlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='included_courses',
            field=models.ManyToManyField(blank=True, related_name='included_in_packages', to='core.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_package',
            field=models.BooleanField(default=False),
        ),
    ]
