# Generated by Django 6.1 on 2026-09-09 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='core.enrollment'),
        ),
    ]
