# Generated by Django 6.1 on 2026-09-19 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_staffprofile_requires_location_login_staffloginlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('kharghar', 'Kharghar'), ('panvel', 'Panvel'), ('koperkhairane', 'Koperkhairane'), ('kamothe', 'Kamothe'), ('ghansoli', 'Ghansoli'), ('nerul', 'Nerul'), ('head_office', 'Head Office')], max_length=50)),
                ('partner_name', models.CharField(max_length=150)),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['branch', 'partner_name'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'partner_name'), name='unique_branch_partner')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBranchClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('kharghar', 'Kharghar'), ('panvel', 'Panvel'), ('koperkhairane', 'Koperkhairane'), ('kamothe', 'Kamothe'), ('ghansoli', 'Ghansoli'), ('nerul', 'Nerul'), ('head_office', 'Head Office')], max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('admissions_count', models.PositiveIntegerField(default=0)),
                ('billing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collection_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rent_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('electricity_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('staff_salary_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('government_fee_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('computer_maintenance_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('internet_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mobile_recharge_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advertisement_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stationery_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('housekeeping_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('travelling_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('miscellaneous_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_expense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_expense_description', models.CharField(blank=True, max_length=250)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('validated', 'Validated'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_monthly_closings', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_monthly_closings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'branch'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPartnerShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=150)),
                ('share_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('share_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250)),
                ('closing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_shares', to='core.monthlybranchclosing')),
            ],
            options={
                'ordering': ['partner_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlybranchclosing',
            constraint=models.UniqueConstraint(fields=('branch', 'year', 'month'), name='unique_branch_month_closing'),
        ),
        migrations.AddConstraint(
            model_name='monthlypartnershare',
            constraint=models.UniqueConstraint(fields=('closing', 'partner_name'), name='unique_monthly_partner_share'),
        ),
    ]
