# Generated by Django 6.1 on 2026-09-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_seed_expense_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybranchclosing',
            name='reserve_fund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
