# Generated by Django 6.1 on 2026-09-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_feepaymentcorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_year',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Reporting year, e.g. 2025 or 2026', null=True),
        ),
    ]
