# Generated by Django 6.1 on 2026-09-26 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_add_admission_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('branch', models.CharField(choices=[('kharghar', 'Kharghar'), ('panvel', 'Panvel'), ('koperkhairane', 'Koperkhairane')], db_index=True, max_length=30)),
                ('contact_type', models.CharField(choices=[('old_student', 'Old Student'), ('school', 'School Contact'), ('college', 'College Contact'), ('other', 'Other')], db_index=True, default='old_student', max_length=30)),
                ('old_course', models.CharField(blank=True, max_length=200)),
                ('old_admission_year', models.PositiveIntegerField(blank=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('permission_status', models.CharField(choices=[('unknown', 'Unknown'), ('allowed', 'Allowed'), ('declined', 'Declined')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('followup', 'Follow Up'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('converted', 'Converted to Enquiry'), ('do_not_contact', 'Do Not Contact')], db_index=True, default='new', max_length=30)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_outreach_contacts', to=settings.AUTH_USER_MODEL)),
                ('converted_enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_sources', to='core.enquiry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_outreach_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'status'], name='outreach_branch_status_idx')],
            },
        ),
    ]
