# Generated by Django 6.1 on 2026-09-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_add_outreach_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachcontact',
            name='normalized_mobile',
            field=models.CharField(blank=True, db_index=True, help_text='Digits-only mobile used for duplicate detection', max_length=15),
        ),
    ]
