# Generated by Django 6.1 on 2026-09-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_add_outreach_normalized_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('profession_business', models.CharField(blank=True, max_length=150, null=True)),
                ('has_existing_institute', models.BooleanField(default=False)),
                ('investment_range', models.CharField(choices=[('undecided', 'Not Decided Yet'), ('below_2', 'Below ₹2 Lakh'), ('2_5', '₹2 - ₹5 Lakh'), ('5_10', '₹5 - ₹10 Lakh'), ('10_plus', '₹10 Lakh+')], default='undecided', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('meeting', 'Meeting'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('followup_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
