# Generated by Django 6.1 on 2026-09-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_franchiseenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='current_status',
            field=models.CharField(blank=True, choices=[('student', 'Student / Studying'), ('working', 'Working Professional'), ('both', 'Working & Studying')], max_length=20, null=True),
        ),
    ]
