# Generated by Django 6.1 on 2026-09-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_add_enquiry_current_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryactivity',
            name='campaign_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
