# Generated by Django 6.1 on 2026-10-02 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_add_enquiry_activity_campaign_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPerformanceReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('score', models.PositiveIntegerField(default=0)),
                ('confirmed_contacts', models.PositiveIntegerField(default=0)),
                ('admissions', models.PositiveIntegerField(default=0)),
                ('gift_description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('given', 'Reward Given')], default='approved', max_length=20)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_staff_rewards', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilled_staff_rewards', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-approved_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'period_start', 'period_end'), name='unique_staff_reward_period')],
            },
        ),
    ]
