# Generated by Django 6.1 on 2026-10-02 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_staffperformancereward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendanceAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('present_days', models.PositiveIntegerField()),
                ('marked_days', models.PositiveIntegerField()),
                ('gift_description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('given', 'Award Given')], default='approved', max_length=20)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_student_attendance_awards', to=settings.AUTH_USER_MODEL)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfilled_student_attendance_awards', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_attendance_awards', to='core.student')),
            ],
            options={
                'ordering': ['-month', '-approved_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'month'), name='unique_student_attendance_award_month')],
            },
        ),
    ]
