# Generated by Django 6.1 on 2026-10-02 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_studentattendanceaward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='reward_points_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentattendanceaward',
            name='reward_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentRewardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='points_entry', to='core.studentattendanceaward')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_reward_entries', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reward_entry', to='core.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reward_entries', to='core.student')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('award__isnull', False), ('enrollment__isnull', True), ('points__gt', 0)), models.Q(('award__isnull', True), ('enrollment__isnull', False), ('points__lt', 0)), _connector='OR'), name='student_reward_entry_valid_source')],
            },
        ),
    ]
