# Generated by Django 6.1 on 2026-10-03 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_enrollment_reward_points_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePaymentDeletionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_payment_id', models.PositiveIntegerField(unique=True)),
                ('receipt_number', models.CharField(max_length=30, unique=True)),
                ('snapshot', models.JSONField()),
                ('reason', models.TextField()),
                ('deleted_by_name', models.CharField(max_length=150)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_fee_receipt_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at', '-id'],
            },
        ),
    ]
