# Generated by Django 6.1 on 2026-10-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_feepaymentdeletionaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybranchclosing',
            name='fresh_collection_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='monthlybranchclosing',
            name='fresh_pending_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='monthlybranchclosing',
            name='old_collection_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='monthlybranchclosing',
            name='other_collection_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
