# Generated by Django 6.1 on 2026-09-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], default='en', max_length=2),
        ),
    ]
