# Generated by Django 6.1 on 2026-09-07 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_quizquestion_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSTopicContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi')], default='en', max_length=2)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('notes_file', models.FileField(blank=True, null=True, upload_to='lms/notes/')),
                ('practice_file', models.FileField(blank=True, null=True, upload_to='lms/practice/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='lms.lmstopic')),
            ],
            options={
                'ordering': ('topic', 'language'),
                'unique_together': {('topic', 'language')},
            },
        ),
    ]
