# Generated by Django 6.1 on 2026-09-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_lmstopiccontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
