# Generated by Django 6.1 on 2026-09-25 08:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_staffattendance'),
        ('lms', '0006_staffquizattempt_stafftopicprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(max_length=200)),
                ('module_order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('learning_outcome', models.TextField(blank=True)),
                ('trainer_steps', models.TextField(blank=True)),
                ('student_practice', models.TextField(blank=True)),
                ('completion_check', models.TextField(blank=True)),
                ('expected_sessions', models.PositiveSmallIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_training_checklist_items', to='core.staffprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_checklist_items', to='core.course')),
                ('lms_topic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_checklist_item', to='lms.lmstopic')),
            ],
            options={
                'ordering': ('course_id', 'module_order', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TrainingDeliveryEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_delivery_records', to='core.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDeliverySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('session_type', models.CharField(choices=[('regular', 'Regular Class'), ('doubt_reteach', 'Doubt Re-teaching'), ('revision', 'Revision')], default='regular', max_length=20)),
                ('session_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('standard_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_delivery_sessions', to='core.staffprofile')),
                ('enrollments', models.ManyToManyField(related_name='teaching_delivery_sessions', through='lms.TrainingDeliveryEnrollment', to='core.enrollment')),
                ('taught_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivered_training_sessions', to='core.staffprofile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_sessions', to='lms.trainingchecklistitem')),
            ],
            options={
                'ordering': ['-session_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='trainingdeliveryenrollment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='lms.trainingdeliverysession'),
        ),
        migrations.CreateModel(
            name='LMSTopicDoubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('cleared', 'Cleared')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('trainer_note', models.TextField(blank=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_topic_doubts', to='core.enrollment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_lms_doubts', to='core.staffprofile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_doubts', to='lms.trainingchecklistitem')),
                ('resolution_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_doubts', to='lms.trainingdeliverysession')),
            ],
            options={
                'ordering': ['status', '-opened_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='trainingdeliveryenrollment',
            unique_together={('session', 'enrollment')},
        ),
    ]
