# Generated by Django 6.1 on 2026-09-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_staffattendance'),
        ('lms', '0007_trainingchecklistitem_trainingdeliveryenrollment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDeliveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_note', models.TextField(blank=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('revised_completion_date', models.DateField(blank=True, null=True)),
                ('revision_reason', models.TextField(blank=True)),
                ('weekly_classes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_course_delivery_plans', to='core.staffprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_delivery_plans', to='core.course')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_delivery_plans', to='core.enrollment')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_course_delivery_plans', to='core.staffprofile')),
                ('start_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_start_plans', to='lms.trainingchecklistitem')),
            ],
            options={
                'unique_together': {('enrollment', 'course')},
            },
        ),
    ]
