# Generated by Django 6.1 on 2026-09-25 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_staffattendance'),
        ('lms', '0008_trainingdeliveryplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdeliveryenrollment',
            name='practice_evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingdeliveryenrollment',
            name='practice_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingdeliveryenrollment',
            name='practice_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_student_lab_practices', to='core.staffprofile'),
        ),
    ]
