# Generated by Django 6.1 on 2026-09-25 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_staffattendance'),
        ('lms', '0009_trainingdeliveryenrollment_practice_evidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('branch', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_assignments_created', to='core.staffprofile')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_teaching_assignments', to='core.enrollment')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_teaching_assignments', to='lms.trainingchecklistitem')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_assignments', to='lms.classroomtrainer')),
            ],
            options={
                'ordering': ('-week_start', 'id'),
                'unique_together': {('enrollment', 'topic', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='TrainerTeachingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taught_on', models.DateField(default=django.utils.timezone.localdate)),
                ('teaching_note', models.TextField()),
                ('lab_completed', models.BooleanField(default=False)),
                ('lab_evidence', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('submitted', 'Awaiting staff approval'), ('approved', 'Approved'), ('rejected', 'Needs correction')], default='submitted', max_length=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('student_response', models.CharField(choices=[('pending', 'Awaiting student'), ('satisfied', 'Satisfied'), ('doubt', 'Has doubt')], default='pending', max_length=12)),
                ('student_note', models.TextField(blank=True)),
                ('student_responded_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_teaching_reports', to='core.staffprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_teaching_reports', to='core.staffprofile')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_teaching_reports', to='lms.classroomtrainer')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_reports', to='lms.weeklyteachingassignment')),
            ],
            options={
                'ordering': ('-submitted_at', '-id'),
            },
        ),
    ]
