# Generated by Django 6.1 on 2026-09-25 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_staffattendance'),
        ('lms', '0010_classroomtrainer_weeklyteachingassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerteachingreport',
            name='coverage_reason',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ClassroomTrainerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_attendance_approved', to='core.staffprofile')),
                ('source_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_credits', to='lms.trainerteachingreport')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_attendance', to='lms.classroomtrainer')),
            ],
            options={
                'ordering': ('-attendance_date', '-id'),
                'unique_together': {('trainer', 'attendance_date')},
            },
        ),
    ]
