# Generated by Django 6.1 on 2026-09-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_trainerteachingreport_coverage_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerteachingreport',
            name='trainer_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
