# Generated by Django 6.1 on 2026-09-29 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0046_franchiseenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSCResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subject', models.CharField(choices=[('maths_1', 'Mathematics Part 1'), ('maths_2', 'Mathematics Part 2'), ('science_1', 'Science & Technology Part 1'), ('science_2', 'Science & Technology Part 2'), ('english', 'English'), ('marathi', 'Marathi'), ('history', 'History & Political Science'), ('geography', 'Geography')], max_length=30)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('previous_paper', 'Previous Year Question Paper'), ('sample_paper', 'Sample Paper'), ('practice', 'MCTI Practice Material')], default='previous_paper', max_length=30)),
                ('medium', models.CharField(choices=[('english', 'English'), ('marathi', 'Marathi'), ('semi_english', 'Semi-English')], default='english', max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('file', models.FileField(blank=True, null=True, upload_to='ssc_exam_resources/')),
                ('is_official_source', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'subject', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SSCStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('mobile', models.CharField(db_index=True, max_length=15)),
                ('school_name', models.CharField(max_length=200)),
                ('medium', models.CharField(choices=[('english', 'English'), ('marathi', 'Marathi'), ('semi_english', 'Semi-English')], max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('consent_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssc_exam_students', to='core.branchlocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSCDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='exam_preparation.sscresource')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='exam_preparation.sscstudent')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
