# Generated by Django 6.1 on 2026-09-29 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_franchiseenquiry'),
        ('exam_preparation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sscstudent',
            name='enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ssc_exam_leads', to='core.enquiry'),
        ),
    ]
