# Generated by Django 6.1 on 2026-10-01 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0048_add_enquiry_activity_campaign_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('content', models.TextField()),
                ('target_wpm', models.PositiveIntegerField(default=20)),
                ('target_accuracy', models.DecimalField(decimal_places=2, default=90, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TypingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('typed_characters', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_attempts', to='core.student')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='typing_practice.typinglesson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_wpm', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('best_accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('best_errors', models.PositiveIntegerField(default=0)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='typing_practice.typinglesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_progress', to='core.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson'), name='unique_student_typing_lesson_progress')],
            },
        ),
    ]
