# Generated by Django 6.1 on 2026-10-01 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_add_enquiry_activity_campaign_key'),
        ('typing_practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('activity_type', models.CharField(choices=[('practice', 'Practice'), ('exam', 'Exam'), ('game', 'Game')], max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('typed_characters', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_activity', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypingExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('target_wpm', models.PositiveIntegerField(default=20)),
                ('target_accuracy', models.DecimalField(decimal_places=2, default=90, max_digits=5)),
                ('duration_seconds', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='typing_practice.typinglesson')),
            ],
        ),
        migrations.CreateModel(
            name='TypingExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('wpm', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('typed_characters', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='typing_practice.typingexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_exam_attempts', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypingGameAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('letter_rush', 'Letter Rush'), ('word_burst', 'Word Burst'), ('speed_60', '60 Second Challenge'), ('accuracy', 'Accuracy Challenge')], max_length=30)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('wpm', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_game_attempts', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypingLevelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_attempts', models.PositiveIntegerField(default=0)),
                ('best_exam_wpm', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('best_exam_accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('exam_passed', models.BooleanField(default=False)),
                ('passed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progress', to='typing_practice.typinglesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_level_progress', to='core.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson'), name='unique_student_typing_level')],
            },
        ),
    ]
