# Generated by Django 6.1 on 2026-10-02 04:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_add_enquiry_activity_campaign_key'),
        ('typing_practice', '0002_typingactivity_typingexam_typingexamattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('student_identifier', models.CharField(max_length=100)),
                ('final_wpm', models.DecimalField(decimal_places=2, max_digits=7)),
                ('final_accuracy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('benchmarks_completed', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='typing_certificate', to='core.student')),
            ],
        ),
    ]
