# Generated by Django 6.1 on 2026-10-02 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_add_enquiry_activity_campaign_key'),
        ('typing_practice', '0003_typingcertificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='typingactivity',
            name='active_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TypingWeeklyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('reward_type', models.CharField(choices=[('consistency', 'Consistent Performer'), ('star', 'Weekly Typing Star'), ('graduate', 'Typing Graduate Discount')], max_length=20)),
                ('status', models.CharField(choices=[('eligible', 'Eligible'), ('approved', 'Approved'), ('given', 'Gift Given / Discount Used'), ('rejected', 'Rejected')], default='eligible', max_length=20)),
                ('qualifying_days', models.PositiveIntegerField(default=0)),
                ('active_minutes', models.PositiveIntegerField(default=0)),
                ('gift_description', models.CharField(blank=True, max_length=255)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_typing_rewards', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='typing_rewards', to='core.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'week_start', 'reward_type'), name='unique_student_week_typing_reward')],
            },
        ),
    ]
