# Generated by Django 6.1 on 2026-10-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typing_practice', '0004_typingactivity_active_seconds_typingweeklyreward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typingweeklyreward',
            name='discount_amount',
        ),
        migrations.AlterField(
            model_name='typingweeklyreward',
            name='reward_type',
            field=models.CharField(choices=[('consistency', 'Consistent Performer'), ('star', 'Weekly Typing Star')], max_length=20),
        ),
        migrations.AlterField(
            model_name='typingweeklyreward',
            name='status',
            field=models.CharField(choices=[('eligible', 'Eligible'), ('approved', 'Approved'), ('given', 'Gift Given'), ('rejected', 'Rejected')], default='eligible', max_length=20),
        ),
    ]
