# Generated by Django 6.1 on 2026-10-02 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_add_enquiry_activity_campaign_key'),
        ('typing_practice', '0005_remove_typingweeklyreward_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typingcertificate',
            name='certificate_type',
            field=models.CharField(choices=[('legacy', 'Previously Issued Achievement'), ('basic', 'English Typing - 30 WPM'), ('master', 'Master in English Typing - 40 WPM')], default='legacy', max_length=10),
        ),
        migrations.AlterField(
            model_name='typingcertificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='typing_certificates', to='core.student'),
        ),
        migrations.AddConstraint(
            model_name='typingcertificate',
            constraint=models.UniqueConstraint(fields=('student', 'certificate_type'), name='unique_typing_certificate_per_type'),
        ),
    ]
